version: '3'
services:
  app:
    build: ./backEnd
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/iot?useSSL=false
      - MQTT_BROKER_URL=tcp://mqtt:1883
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
      - mqtt

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3306:3306"
    volumes:
      - ./backEnd/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db-data:/var/lib/mysql

  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./backEnd/src/main/resources/mosquitto.conf:/mosquitto/config/mosquitto.conf

  client:
    build: ./iotclient
    environment:
      - SERVER=tcp://mqtt:1883
    restart: always
    depends_on:
      - mqtt

  sim:
    build: ./iotsimulator
    ports:
      - "5000:5000"
    environment:
      - MQTT_BROKER=mqtt
      - MQTT_PORT=1883
    restart: always
    depends_on:
      - mqtt

volumes:
  db-data:
